# Generated by Django 2.1.5 on 2019-01-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('upvote', models.IntegerField()),
                ('description', models.TextField()),
                ('sentiment_score', models.FloatField()),
                ('story_type', models.CharField(max_length=64)),
                ('hacker_news_id', models.IntegerField()),
                ('posted_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
